### ISSUE TITLE
Complete README to explain how to use mysqltosqlite.py script

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#12]
This is really important. This should also include the commands about how to create the venv. A requirements file (for pip) should also be created to list Python (3?) deps.

**Comment by florentk** [comment]
@kelson42  j'ai ajouté une section dans le fichier  README  dans 61b3708. Pour l'installation des dépendances pip et venv, faut que je regarde comment on fait, pour l'instant j'ai juste ajouté la commande pour installer les paquets sur debian/ubuntu.

**Comment by kelson42** [comment]
@florentk Thx, will try to have a look ASAP

**Comment by florentk** [comment]
@kelson42 done in a3365e3

**Comment by kelson42** [comment]
@florentk Thx
