### ISSUE TITLE
How to get custom logo.png and favicon.ico

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#13]
On wiki.openzim.org, both are missing, and it seems there is not place in the Docker volume to place them.

**Comment by florentk** [comment]
@kelson42  Both must be in /images dir volume. Theses files are in tarball , and two symlinks are created toward theses files after volumes extraction.  In my pc, the logo and favicon are ok, can you check if this files are in /images ?

**Comment by kelson42** [comment]
@florentk Works fine thx
