### ISSUE TITLE
Sqlite maintenance script should be run time to time

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#19]
To optimize the database:
https://www.mediawiki.org/wiki/Manual:Sqlite.php

**Comment by kelson42** [comment]
@florentk I have run it on the wiki.kiwix.org and have been able to save 30% of the space of the sqlite DB. This has also - considering what the documentation says - a performance impact. Would you be able to make a cron in the Docker to run this one time a week?

**Comment by florentk** [comment]
done in 78797cb
