### ISSUE TITLE
Suggestions are empty/broken

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#2]
In the top-right search suggestions are broken, I never get anything at https://mediawiki.openzim.org. If you compare with for example http://wiki.kiwix.org, you will see it work there. I suspect that an extension is responsible for that and has not been installed properly.

**Comment by florentk** [comment]
when I disable Wikibase extension, the suggestion works. But Wikibase seem correctly configured ...

**Comment by kelson42** [comment]
@florentk Hmmm... I do not really see why we have Wikibase Extension? Does that come from WikiFundi 1.0? We should not need it.

**Comment by florentk** [comment]
Wikibase is configured in LocalSetting.php (may be the custom) of WikiFundi 1.0, it's for that I had add this extension.

**Comment by kelson42** [comment]
@florentk OK... I can not remember at all why... I would recommend to deactivate it with a comment pointing to that ticket... and close the ticket. Anyway this has not to be in the base Mediawiki IMO, so please move this to wikifundi.

**Comment by florentk** [comment]
@kelson42  or maybe I had install Wikibase to fix a error in pages : 
`Lua error in Module:Authority_control at line 423: attempt to index field 'wikibase' (a nil value).`

**Comment by florentk** [comment]
Wikibase is not installed in last commit 121a5aa

**Comment by kelson42** [comment]
@florentk OK, then remove it. I understand the Lua error. We should probably patch here somehow the lua code to return empty string or something similar. Wikibase is use to import data of wikidata.org.
