### ISSUE TITLE
Mysql compatible backup solution

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#22]
Improve the export data script we already have to:
* export all the data even if MySQL is used
* Allow to put a password to the export data URL to secure it. A password which would be set as a environment variable to the docker container

**Comment by florentk** [comment]
export mysql data is defined as a weekly cron cbdb4e78bf
a token is added in the URL to export data. The token is defined in  .export_token file of data directory (instead docker environnement variable) e29074a45579

**Comment by kelson42** [comment]
@florentk Why not having an env_variable easy to set at the container creation? Seems a lot easier than a file!

**Comment by florentk** [comment]
@kelson42 I thought it would be a confidentiality problem to define the variable in sloppy, but actualy no, I would change that

**Comment by florentk** [comment]
@kelson42 I've add un env. variable to set the secret token and I've update the REAME and the container on Sloppy.
