### ISSUE TITLE
visual editor does not display images properly

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#24]
For example at https://www.openzim.org/wiki/OpenZIM?veaction=edit, the image is not found.

**Comment by florentk** [comment]
this seem is the same bug : https://stackoverflow.com/questions/34018280/image-not-found-in-visual-editor-mediawiki

**Comment by kelson42** [comment]
@florentk so?

**Comment by florentk** [comment]
LocalSetting.custom.php has been updated for openzim and kiwix wiki to set the domain name and allows to had good url image in visual editor
