### ISSUE TITLE
[Question] Where do I put custom skins?

### ISSUE THREAD

**Issue by zecbmo** [openzim/mediawiki-docker#33]
Very new to this. 

I want to install a custom skin and have updated the localsettings.custom.php but where do I upload the skin files to? 
Do I need to mount a different volume for this?

**Comment by kelson42** [comment]
@rgaudin Not fully sure about the answer, but would mount an external volume for the `/skin` directory? Does that sounds proper?

**Comment by kelson42** [comment]
@rgaudin ?

**Comment by rgaudin** [comment]
Yes, I believe the best option is to mount your `Foo` skin's folder into `/var/www/html/w/skins` and use `wfLoadSkin( 'Foo' );` in your `Localsettings.custom.php`
