### ISSUE TITLE
Mediawiki block functions seems to block the reverse-proxy IP 

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#34]
instead of the real user IP (which should be taken from the reverse-proxy via the `x-forwarded-for` HTTP request header:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

**Comment by rgaudin** [comment]
This is a custom configuration for the deployment and not part of the image.

On Sloppy, we do need it. For the record, I am posting here the extra config to make it work:

```php
$wgUseCdn = true;
$wgCdnServersNoPurge = [];
$wgCdnServersNoPurge[] = "127.0.0.1";
$wgCdnServersNoPurge[] = "192.168.18.0/24";
```

<img width="397" alt="Screen Shot 2022-03-14 at 10 38 54" src="https://user-images.githubusercontent.com/57929/158156205-e3f1ff75-7686-4faa-baa3-5736154423b7.png">
