### ISSUE TITLE
Introduce extension:iframe

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#35]
This is necessary in following wikis:
* wiki.kiwix.org
* Wiki.openzim.org

To create page base on widget of library.kiwix.org, see https://github.com/kiwix/libkiwix/issues/585

Please create a key for library.kiwix,org and dev.library.kiwix.org, more details at https://www.mediawiki.org/wiki/Extension:Iframe

**Comment by rgaudin** [comment]
Done.

Keys are `library` and `dev.library`

Sample wikicode:

```wiki
<iframe key="library" level="" path="mali-pour-les-nuls_fr_all/" />
```

<img width="974" alt="Screen Shot 2022-08-15 at 09 38 25" src="https://user-images.githubusercontent.com/57929/184613047-c008ed61-fe73-4aff-910a-50c7701a74de.png">


**Note**: path must not start with a `/`.

**Comment by kelson42** [comment]
@rgaudin Thank you.
@juuz0 You could test it with dev.library.kiwix.org once https://github.com/kiwix/libkiwix/pull/797 will be merged.

**Comment by juuz0** [comment]
Thanks!
