### ISSUE TITLE
What about openzim/mediawiki

### ISSUE THREAD

**Issue by kelson42** [openzim/mediawiki-docker#36]
An image is stored at https://hub.docker.com/r/openzim/mediawiki. This image seems not updated, so here are the questions:
* Is that not really updated?
* Why this is not updated?
* Should we remove it or from now update it?

**Comment by rgaudin** [comment]
> * Is that not really updated?

Yes

> * Why this is not updated?

We decided to move this project under our *offspot* umbrella. As for all offspot projects, there is no matching organization in dockerhub so the image is only available on ghcr (direct link on repo homepage in github).

> * Should we remove it or from now update it?

When we moved we discussed removing it but we were not sure who else is using it and how it could affect them so we didn't. I'm in favor or removing it now.

**Comment by kelson42** [comment]
OK, done
