### ISSUE TITLE
Docker build fails due to MwEmbedSupport

### ISSUE THREAD

**Issue by rgaudin** [openzim/mediawiki-docker#6]
With the `1.32` release of Mediawiki, [MwEmbedSupport](https://www.mediawiki.org/wiki/Extension:MwEmbedSupport) has been archived and is thus not available [through the API](https://wikiapiary.com/wiki/Extension:MwEmbedSupport).

Docker build thus fails at [add_mw_extension](https://github.com/openzim/mediawiki-docker/blob/master/Dockerfile#L135) step.

**Comment by florentk** [comment]
We cannot use 1.32 version because this is an alpha version. I disabled the download through the API, and download a archived tar from the GIT. In futur,  disable  MwEmbedSupport with 1.32 version because is  will be not longer needed by TimedMediaHandler extension.
The last commit is not tested.

**Comment by kelson42** [comment]
@florentk I do not understand, do we switch automatically to new versions of Mediawiki? I think we should stick to one version, and make MW update manually.

**Comment by florentk** [comment]
@kelson42 switch to 1.32 version is not needed with the patch to get the archived version of MwEmbedSupport. But IF we want one day switch to 1.32, MwEmbedSupport must be disabled.

**Comment by kelson42** [comment]
@florentk Got it. Thank you very much on this.

**Comment by kelson42** [comment]
This has been fixed on master
