### ISSUE TITLE
www.openzim.org need additional extrensions

### ISSUE THREAD

**Issue by florentk** [openzim/mediawiki-docker#8]
To migrate the openzim mediawiki to this docker image, we need additional extensions :

- RSS
- TorBlock  
- MatomoAnalytics
- Bad Behavior
- ConfirmEdit (for Captcha)

**Comment by kelson42** [comment]
@florentk What should I do exactly here? Can I just put these extensions in a volume to be mounted and then it will work? Otherwise, we should maybe try to make them directly in the docker image?

**Comment by florentk** [comment]
@kelson42 I do not know at the base there was no use a volume for the extensions, so the question now is whether we should put new extensions in the image or use another image for openzim wiki. Or I can configure a volume for extensions.

**Comment by kelson42** [comment]
@florentk I'm against having dedicated images for dedicated wikis. So we have to put everything we need in the Mediawiki image... Seems OK to me.
