### ISSUE TITLE
$wgEmailConfirmToEdit = true; causes the wiki to be inaccessible for anonymous users

### ISSUE THREAD

**Issue by florentk** [openzim/mediawiki-docker#9]
https://phabricator.wikimedia.org/T143790

**Comment by florentk** [comment]
Fix in add $wgBlockDisablesLogin = false
It's ok ?

**Comment by kelson42** [comment]
@florentk It seems T143790 is fixed, why not using it?

**Comment by kelson42** [comment]
@florentk A feedback about that would be welcome. Do you know more?

**Comment by florentk** [comment]
@florentk Actually, this concern exclusively the config of OpenZim/Kiwix wiki, not the defaut config of Mediawiki image
